# ReadTheDocs configuration for Citrus Engine
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - doxygen
    - graphviz
  jobs:
    pre_build:
      # Generate Doxygen XML documentation
      - doxygen Doxyfile

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

python:
  install:
    - requirements: docs/requirements.txt
